# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/runs',
                'doc_host': 'https://gzquse.github.io',
                'git_url': 'https://github.com/gzquse/runs',
                'lib_path': 'runs'},
  'syms': {'runs.core': {'runs.core.foo': ('core.html#foo', 'runs/core.py')}}}
